import "./globals.css"

import type {Metadata} from "next"
import {Inter} from "next/font/google"
import {Poppins} from "next/font/google"

import ShopeContext from "@/context/ShopeContext"

import Left from "@/components/Left/Left"
import Right from "@/components/Right/Right"
import Navbar from "@/components/Navbar/Navbar"
import Footer from "@/components/Footer/Footer"

const inter = Inter({subsets: ["latin"]})

const poppins = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "E-Commerce Shop",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={poppins.className}>
        <div className='bg-slate-50'>
          <ShopeContext>
            <Navbar />
            <div className='app'>
              <div>
                <Left />
              </div>
              <div>{children}</div>
              <div>
                <Right />
              </div>
            </div>
            <Footer />
          </ShopeContext>
        </div>
      </body>
    </html>
  )
}
